package com.game.biz.model.enumeration;

/**
 * The EventType enumeration.
 */
public enum EventType {
    BADGE_PRO, BADGE_MASTER_AVAILABLE, BADGE_LEGEND_AVAILABLE, POINTS_RESET, BADGE_PRO_RESETTED, BADGE_MASTER_RESETTED, PRESENT_WON,
    EXCHANGE_PRO_FOR_MASTER, EXCHANGE_MASTER_FOR_LEGEND
}
